### ISSUE TITLE
Could not start a new session

### ISSUE THREAD

**Issue by XenWayne** [cssxsh/mirai-selenium-plugin#11]
2022-01-27 13:08:22 W/bilibili-helper: 获取动态620409911402125367快照失败
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 255
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'xwserverubuntu', ip: '10.0.0.12', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-96-generic', java.version: '17.0.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless, --width=768, --height=1024], prefs: {browser.aboutConfig.showWarning: false, devtools.responsive.touchSimulation.enabled: true, devtools.responsive.userAgent: Mozilla/5.0 (iPad; CPU OS 1..., devtools.responsive.viewport.height: 1024, devtools.responsive.viewport.pixelRatio: 3, devtools.responsive.viewport.width: 768, general.useragent.override: Mozilla/5.0 (iPad; CPU OS 1..., general.warnOnAboutConfig: false, webgl.disabled: true}}, pageLoadStrategy: normal}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless, --width=768, --height=1024], prefs: {browser.aboutConfig.showWarning: false, devtools.responsive.touchSimulation.enabled: true, devtools.responsive.userAgent: Mozilla/5.0 (iPad; CPU OS 1..., devtools.responsive.viewport.height: 1024, devtools.responsive.viewport.pixelRatio: 3, devtools.responsive.viewport.width: 768, general.useragent.override: Mozilla/5.0 (iPad; CPU OS 1..., general.warnOnAboutConfig: false, webgl.disabled: true}}, pageLoadStrategy: normal}}]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:151)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:198)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:194)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$3.invoke(SeleniumInit.kt:470)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$3.invoke(SeleniumInit.kt:456)
        at xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(SeleniumTool.kt:74)
        at xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:57)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2.driver(BiliUtils.kt:82)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2.getValue(BiliUtils.kt:102)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.getDriver(BiliUtils.kt:79)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot(BiliUtils.kt:209)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot(BiliUtils.kt:240)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot$default(BiliUtils.kt:238)
        at xyz.cssxsh.mirai.plugin.BiliContentKt.screenshot(BiliContent.kt:71)
        at xyz.cssxsh.mirai.plugin.BiliContentKt.content(BiliContent.kt:23)
        at xyz.cssxsh.mirai.plugin.BiliContentKt$content$1.invokeSuspend(BiliContent.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by cssxsh** [comment]
有可能是 `geckodriver` 没有执行权限, 检查一下 `data/mirai-selenium-plugin/selenium` 下的执行权限
或者 `firefox` 浏览器 版本不合适，`/selenium firefox` 可以绿色安装最新发布版

**Comment by cssxsh** [comment]
with https://stackoverflow.com/questions/67090130/webdriverexception-process-unexpectedly-closed-with-status-255-selenium-ge
firefox 和 驱动器版本匹配问题
插件获取的是最新的浏览器驱动。

**Comment by cssxsh** [comment]
似乎和 连接的ssh 客户端中开启了 x11 转发有关

**Comment by cssxsh** [comment]
Xshell 的例子
![image](https://user-images.githubusercontent.com/32539286/221138109-efc71175-064c-44a6-9e68-8a64be635d3b.png)
