### ISSUE TITLE
获取动态快照失败

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/mirai-selenium-plugin#13]
```
2022-02-05 17:25:47 W/bilibili-helper: 获取动态623692103931938579快照失败
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$3.invoke(SeleniumInit.kt:482)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$3.invoke(SeleniumInit.kt:464)
        at xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(SeleniumTool.kt:74)
        at xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:59)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2.driver(BiliUtils.kt:82)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2.getValue(BiliUtils.kt:102)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.getDriver(BiliUtils.kt:79)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot(BiliUtils.kt:209)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot(BiliUtils.kt:240)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot$default(BiliUtils.kt:238)
        at xyz.cssxsh.mirai.plugin.BiliContentKt.screenshot(BiliContent.kt:70)
        at xyz.cssxsh.mirai.plugin.BiliContentKt.content(BiliContent.kt:22)
        at xyz.cssxsh.mirai.plugin.BiliDynamicLoader.build(BiliTasker.kt:245)
        at xyz.cssxsh.mirai.plugin.BiliDynamicLoader.build(BiliTasker.kt:230)
        at xyz.cssxsh.mirai.plugin.AbstractTasker$send$1$1.invokeSuspend(BiliTasker.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'raspberrypi', ip: '192.168.31.153', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.4.0-1050-raspi', java.version: '17.0.1'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:226)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
        ... 27 more
```

**Comment by LaoLittle** [comment]
> 2022-02-05 17:25:47 W/bilibili-helper: 获取动态623692103931938579快照失败 org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576) at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245) at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:161) at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:137) at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:133) at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$3.invoke(SeleniumInit.kt:482) at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$3.invoke(SeleniumInit.kt:464) at xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(SeleniumTool.kt:74) at xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:59) at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2.driver(BiliUtils.kt:82) at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2.getValue(BiliUtils.kt:102) at xyz.cssxsh.mirai.plugin.BiliUtilsKt.getDriver(BiliUtils.kt:79) at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot(BiliUtils.kt:209) at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot(BiliUtils.kt:240) at xyz.cssxsh.mirai.plugin.BiliUtilsKt.screenshot$default(BiliUtils.kt:238) at xyz.cssxsh.mirai.plugin.BiliContentKt.screenshot(BiliContent.kt:70) at xyz.cssxsh.mirai.plugin.BiliContentKt.content(BiliContent.kt:22) at xyz.cssxsh.mirai.plugin.BiliDynamicLoader.build(BiliTasker.kt:245) at xyz.cssxsh.mirai.plugin.BiliDynamicLoader.build(BiliTasker.kt:230) at xyz.cssxsh.mirai.plugin.AbstractTasker$send$1$1.invokeSuspend(BiliTasker.kt:69) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely. Build info: version: '4.1.2', revision: '9a5a329c5a' System info: host: 'raspberrypi', ip: '192.168.31.153', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.4.0-1050-raspi', java.version: '17.0.1' Driver info: driver.version: FirefoxDriver at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:226) at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558) ... 27 more

**Comment by LaoLittle** [comment]
这是订阅动态出现的问题

**Comment by LaoLittle** [comment]
template:
```
@#username##uid 动态
链接: #link
#images
#screenshot
```

**Comment by LaoLittle** [comment]
selenium config:
```
# Chrome/Chromium 二进制文件路径
chrome: ''
# Edge 二进制文件路径
edge: ''
# Firefox 二进制文件路径
firefox: ''
```

```
# 截图UA
user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43'
# 截图宽度
width: 768
# 截图高度
height: 1024
# 截图像素比
pixel_ratio: 3
# 无头模式（后台模式）
headless: true
# 代理地址
proxy: ''
# 启用日志文件
log: false
# 指定使用的浏览器，Chrome/Firefox
browser: ''
# 指定使用的Factory
factory: ktor

```

**Comment by LaoLittle** [comment]
mirai
selenium版本 2.0.7

**Comment by ghost** [comment]
请问一下问题解决了吗，目前我也这个问题。
