### ISSUE TITLE
why

### ISSUE THREAD

**Issue by gatesx** [cssxsh/mirai-selenium-plugin#15]
iTXTech Mirai Console Loader version 1.2.2-60c67fb
windows sever 2019
Java 17 / 16 / 11一样
> 截图 gatesx.cn
正在截图。。。请稍等
```
2022-03-20 15:23:33 W/stderr: Exception in thread "Thread-36" java.lang.LinkageError: loader constraint violation: when resolving method 'org.openqa.selenium.remote.RemoteWebDriver xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(xyz.cssxsh.selenium.RemoteWebDriverConfig)' the class loader 'imagepluginv0.0.3.jar' @32e54a9d of the current class, org/Command/PhantomTools, and the class loader 'mirai-selenium-plugin-2.0.8.mirai.jar' @40e37b06 for the method's defining class, xyz/cssxsh/mirai/plugin/MiraiSeleniumPlugin, have different Class objects for the type xyz/cssxsh/selenium/RemoteWebDriverConfig used in the signature (org.Command.PhantomTools is in unnamed module of loader 'imagepluginv0.0.3.jar' @32e54a9d, parent loader net.mamoe.mirai.console.internal.plugin.DynLibClassLoader @24934262; xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin is in unnamed module of loader 'mirai-selenium-plugin-2.0.8.mirai.jar' @40e37b06, parent loader net.mamoe.mirai.console.internal.plugin.DynLibClassLoader @24934262)
2022-03-20 15:23:33 W/stderr:   at imagepluginv0.0.3.jar//org.Command.PhantomTools.lambda$onCommand$0(PhantomTools.java:37)
2022-03-20 15:23:33 W/stderr:   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by cssxsh** [comment]
mirai 2.11.0-M1 有bug
