### ISSUE TITLE
2.11.0 类加载错误

### ISSUE THREAD

**Issue by 1301715759** [cssxsh/mirai-selenium-plugin#19]
不知道最近啥时候mirai更新后出现了一堆问题，BA-imageplugin是我改写别人的简单截图插件。。前段时间一直正常运行，忘了什么时候重启更新后出现。

```
2022-05-24 01:43:31 W/stderr: Exception in thread "Thread-23" java.lang.LinkageError: loader constraint violation: when resolving method 'org.openqa.selenium.remote.RemoteWebDriver xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(xyz.cssxsh.selenium.RemoteWebDriverConfig)' the class loader 'BA-imageplugin-1.0-SNAPSHOT.mirai.jar' @2100d047 of the current class, xyz/cssxsh/mirai/plugin/MiraiSeleniumPlugin, and the class loader 'mirai-selenium-plugin-2.1.0.mirai.jar' @1c8f6a90 for the method's defining class, xyz/cssxsh/selenium/SeleniumToolKt, have different Class objects for the type xyz/cssxsh/selenium/RemoteWebDriverConfig used in the signature (xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin is in unnamed module of loader 'BA-imageplugin-1.0-SNAPSHOT.mirai.jar' @2100d047, parent loader net.mamoe.mirai.console.internal.plugin.DynLibClassLoader @14b0e127; xyz.cssxsh.selenium.SeleniumToolKt is in unnamed module of loader 'mirai-selenium-plugin-2.1.0.mirai.jar' @1c8f6a90, parent loader net.mamoe.mirai.console.internal.plugin.DynLibClassLoader @14b0e127)
2022-05-24 01:43:32 W/stderr:   at BA-imageplugin-1.0-SNAPSHOT.mirai.jar//xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:57)
2022-05-24 01:43:32 W/stderr:   at BA-imageplugin-1.0-SNAPSHOT.mirai.jar//org.Command.PhantomTools.lambda$onCommand$0(PhantomTools.java:42)
2022-05-24 01:43:32 W/stderr:   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by cssxsh** [comment]
2.1.0 的更新中 https://github.com/cssxsh/mirai-selenium-plugin/commit/5ba3ab3820932824b4b48fca8243519c55acbb44 我重命名了部分包名
应该是这个的原因
你可能需要重新编译你的插件

**Comment by 1301715759** [comment]
![image](https://user-images.githubusercontent.com/44659174/170461123-1638aa21-e935-41e7-a4af-6efce112b52b.png)
编译似乎没问题（这个包名没改，有问题的我已经改了），看提示窗口报错是这个包出的问题？

重新编译了，还是一样的报错
![image](https://user-images.githubusercontent.com/44659174/170462966-343be463-fc37-4eac-934f-fb2046fc46a4.png)

**Comment by cssxsh** [comment]
> 2022-05-24 01:43:32 W/stderr:   at BA-imageplugin-1.0-SNAPSHOT.mirai.jar//xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:57)

你好像把我的插件打包到你的插件里面了

**Comment by cssxsh** [comment]
给一下 dependencies  配置，还有你的打包方法

**Comment by cssxsh** [comment]
with https://github.com/liuqianpan2008/imageplugin/commit/ee2a3ba100315c9afab610bccd3e78a5f89abfbd
