### ISSUE TITLE
用2.2.1版本插件启动的时候报错

### ISSUE THREAD

**Issue by Anluoxuan1** [cssxsh/mirai-selenium-plugin#21]
```
2022-07-24 17:50:25 I/main: Starting mirai-console...
2022-07-24 17:50:25 I/main: Backend: version 2.12.0, built on 2022-07-03 10:57:58.
2022-07-24 17:50:25 I/main: Frontend Terminal: version 2.12.0, provided by Mamoe Technologies
2022-07-24 17:50:25 I/main: Welcome to visit https://mirai.mamoe.net/
2022-07-24 17:50:25 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-07-24 17:50:25 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-07-24 17:50:25 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-07-24 17:50:26 W/mirai-skia-plugin: Linked class io.ktor.client.engine.okhttp.OkHttp in bilibili-helper-1.6.1.jar but plugin not depend on it.
2022-07-24 17:50:26 W/mirai-skia-plugin: Class loading logic may change in feature.
2022-07-24 17:50:26 I/plugin: Successfully loaded plugin SimpleGroupAuth v0.1.1
2022-07-24 17:50:26 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-07-24 17:50:26 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-07-24 17:50:26 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.5.2
2022-07-24 17:50:26 I/plugin: Cannot load plugin mirai-selenium-plugin v2.2.1
2022-07-24 17:50:26 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading mirai-selenium-plugin v2.2.1
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:258)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:93)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:149)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:178)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/devtools/DevToolsException
        at mirai-selenium-plugin-2.2.1.jar//xyz.cssxsh.mirai.selenium.MiraiSeleniumPlugin.onLoad(MiraiSeleniumPlugin.kt:95)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:248)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:256)
        ... 40 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.devtools.DevToolsException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:385)
        ... 43 more

2022-07-24 17:50:26 W/mirai-skia-plugin: Linked class org.jetbrains.skiko.OsArch_jvmKt in mirai-skia-plugin-1.1.4.mirai2.jar but plugin not depend on it.
2022-07-24 17:50:26 W/mirai-skia-plugin: Class loading logic may change in feature.
```

中间一串加载的时候出错，而且插件文件夹有两个mirai-selenium

**Comment by cssxsh** [comment]
mcl 该升级了

https://github.com/iTXTech/mirai-console-loader/releases/tag/v2.1.0

**Comment by Anluoxuan1** [comment]
升级之后直接没法获取公告了。。。是网络问题吗，不管挂不挂梯子都是这个提示
```
  19:45:29 [INFO] iTXTech Mirai Console Loader version 2.1.0-71ec418
  19:45:29 [INFO] https://github.com/iTXTech/mirai-console-loader
  19:45:29 [INFO] This program is licensed under GNU AGPL v3
  19:46:11 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-console"
  19:46:20 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-console-terminal"
  19:46:29 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-core-all"
  19:47:20 [ERROR] Failed to fetch announcement for "org.itxtech:mcl-addon"
```

**Comment by cssxsh** [comment]
> 升级之后直接没法获取公告了。。。是网络问题吗，不管挂不挂梯子都是这个提示
> 
> ```
>   19:45:29 [INFO] iTXTech Mirai Console Loader version 2.1.0-71ec418
>   19:45:29 [INFO] https://github.com/iTXTech/mirai-console-loader
>   19:45:29 [INFO] This program is licensed under GNU AGPL v3
>   19:46:11 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-console"
>   19:46:20 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-console-terminal"
>   19:46:29 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-core-all"
>   19:47:20 [ERROR] Failed to fetch announcement for "org.itxtech:mcl-addon"
> ```

https://mirai.mamoe.net/post/10171
