### ISSUE TITLE
Linux Ubuntu 22.10 (GNU/Linux 5.19.0-29-generic aarch64)

### ISSUE THREAD

**Issue by zxmacc** [cssxsh/mirai-selenium-plugin#24]
ARM处理器
/selenium setup和/selenium chromium后
使用/selenium chart指令报错，大佬能帮忙看一下吗
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'ubuntu', ip: '127.0.1.1'
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:553)
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:228)
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:156)
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
        at mirai-selenium-plugin-2.2.5.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt$setupChromeDriver$2.invoke(SeleniumInit.kt:454)
        at mirai-selenium-plugin-2.2.5.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt$setupChromeDriver$2.invoke(SeleniumInit.kt:434)
        at mirai-selenium-plugin-2.2.5.mirai2.jar//xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(SeleniumTool.kt:106)
        at mirai-selenium-plugin-2.2.5.mirai2.jar//xyz.cssxsh.mirai.selenium.command.SeleniumCommand.chart(SeleniumCommand.kt:228)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '5.19.0-29-generic', java.version: '17.0.5'
Driver info: driver.version: ChromeDriver
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.remote.service.DriverService.start(DriverService.java:244)
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
        at mirai-selenium-plugin-2.2.5.mirai2.jar[shared]//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
        ... 35 more
```

然后我是想用这个插件，https://github.com/liuqianpan2008/imageplugin ，然后发现插件跑不了，报错，就来看了一下前置，然后前置也这样，然后我就懵了

**Comment by zxmacc** [comment]
我在tmux里运行的

**Comment by cssxsh** [comment]
> os.arch: 'aarch64'

https://github.com/cssxsh/mirai-selenium-plugin/issues/16

这需要对 ARM64 环境特殊处理，很麻烦

**Comment by zxmacc** [comment]
https://github.com/cssxsh/mirai-selenium-plugin/issues/16#issuecomment-1187593812
好吧，那个，我看了一下，有点不太懂，我现在装了那个[https://pkgs.org/](https://pkgs.org/search/?q=chromedriver)上面的arm版的chrome，然后是需要去插件的配置文件里指定一下嘛
`
browser: 'Chromium'
factory: netty
arguments: []`

**Comment by zxmacc** [comment]
`root@ubuntu:~# -Dwebdriver.chrome.driver=/usr/bin/chromedriver
-bash: -Dwebdriver.chrome.driver=/usr/bin/chromedriver: No such file or directory
`
好像不行，淦

**Comment by cssxsh** [comment]
> -Dwebdriver.chrome.driver=/usr/bin/chromedriver

这需要你编辑 mcl 那个文件， 在 `-jar` 前面加上
即 `$JAVA_BINARY -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar mcl.jar`
