### ISSUE TITLE
求助，浏览器不受支持的问题

### ISSUE THREAD

**Issue by zxmacc** [cssxsh/mirai-selenium-plugin#26]
```
2023-04-04 17:23:48 W/mirai-selenium-plugin: 浏览器  不受支持
java.lang.UnsupportedOperationException: 默认浏览器为空
        at mirai-selenium-plugin-2.3.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt.setupWebDriver(SeleniumInit.kt:176)
        at imagepluginv0.0.3.jar//xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.setup(MiraiSeleniumPlugin.kt:41)
        at imagepluginv0.0.3.jar//org.imageplugin.onEnable(imageplugin.java:34)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:232)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:347)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
```

 版本为Mirai consosle 2.14.0
服务器为腾讯轻量云cpu E5-26xx v4，系统ubuntu，22.04 LTS
尝试过root用户，ubuntu用户，都是这样
尝试过自行下载浏览器，浏览器为ungoogled-chromium_111.0.5563.115_1.vaapi_linux
主要是想使用这个插件imagepluginv0.0.3.jar（原仓库已删除）和bilibili help

**Comment by zxmacc** [comment]
自行下载的浏览器链接https://github.com/macchrome/linchrome/releases
imageplugin frok仓库https://github.com/zxmacc/imageplugin

**Comment by zxmacc** [comment]
两个配置文件
# MiraiBrowserConfig.yml
 Chrome/Chromium 二进制文件路径
chrome: '/home/ubuntu/mcl/data/xyz.cssxsh.mirai.plugin.mirai-selenium-plugin/ungoogled-chromium_111.0.5563.115_1.vaapi_linux/chrome'
 Edge 二进制文件路径
edge: ''
 Firefox 二进制文件路径
firefox: '/root/mcl/data/xyz.cssxsh.mirai.plugin.mirai-selenium-plugin/Firefox-v111.0.1-linux/firefox'

# MiraiSeleniumConfig.yml
驱动文件过期时间，默认一星期 (单位：天)
expires: 7
 清理浏览器驱动，默认30 (单位：分钟)
destroy: 30
 截图UA
user_agent: 'Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1'
截图宽度
width: 768
截图高度
height: 1024
 无头模式（后台模式）
headless: false
 代理地址
proxy: ''
User Preferences
preferences: {}
启用日志文件
log: true
 指定使用的浏览器，Chrome/Chromium/Firefox/Edge
browser: 'Chrome'
 指定使用的Factory
factory: netty
 自定义 arguments
arguments: [--no-sandbox,--disable-dev-shm-usage]

**Comment by cssxsh** [comment]
[imageplugin](https://github.com/zxmacc/imageplugin)
本身的问题，它没有调用配置里的浏览器
