### ISSUE TITLE
/selenium setup时出错

### ISSUE THREAD

**Issue by anti-zey** [cssxsh/mirai-selenium-plugin#28]
操作系统：
```Linux version 3.10.0 (mockbuild@builder2.eng.sw.ru) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Thu Sep 23 18:26:47 MSK 2021```

日志：
```
> selenium setup
??????, flush: true
2023-06-07 10:38:11 W/mirai-selenium-plugin: ??????????
java.io.IOException: Cannot run program "tar" (in directory "/root/mms/data/xyz.cssxsh.mirai.plugin.mirai-selenium-plugin/selenium"): error=0, Failed to exec spawn helper: pid: 3384, exit value: 127
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at mirai-selenium-plugin-2.2.4.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt.setupFirefoxDriver(SeleniumInit.kt:513)
        at mirai-selenium-plugin-2.2.4.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt.setupWebDriver(SeleniumInit.kt:229)
        at mirai-selenium-plugin-2.2.4.mirai2.jar//xyz.cssxsh.mirai.selenium.MiraiSeleniumPlugin.setup(MiraiSeleniumPlugin.kt:47)
        at mirai-selenium-plugin-2.2.4.mirai2.jar//xyz.cssxsh.mirai.selenium.command.SeleniumCommand.setup(SeleniumCommand.kt:35)
        at mirai-selenium-plugin-2.2.4.mirai2.jar//xyz.cssxsh.mirai.selenium.command.SeleniumCommand.setup$default(SeleniumCommand.kt:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 3384, exit value: 127
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 31 more
```

**Comment by cssxsh** [comment]
> Cannot run program "tar"

缺少解压工具

另外你没有汇报操作系统的相关信息，所以我也无法给出建议

**Comment by anti-zey** [comment]
> > Cannot run program "tar"
> 
> 缺少解压工具
> 
> 另外你没有汇报操作系统的相关信息，所以我也无法给出建议

centos7，而且tar命令可以运行

**Comment by cssxsh** [comment]
> /root/mms/...

目测你是 root 敢死队

**Comment by anti-zey** [comment]
> > /root/mms/...
> 
> 目测你是 root 敢死队

草什么意思）

**Comment by cssxsh** [comment]
@anti-zey 

https://github.com/cssxsh/mirai-selenium-plugin/actions/runs/5297968270

改成使用 java 代码解压，而不是命令行了
