### ISSUE TITLE
Multi input/output stream coders are not yet supported

### ISSUE THREAD

**Issue by seven7a** [cssxsh/mirai-selenium-plugin#29]
环境：windows server 2022 ,JAVA SE 20
mirai版本:2.15.0
插件版本:2.5.0
已经做过的尝试，删除data相应文件夹，删除config相关文件夹，更新插件版本，更新mirai版本，删除plugin-libraries并重新下载未解决问题，已经验证下载的压缩包可以被其他压缩软件打开

chrome解压失败
```
2023-09-01 19:13:42 E/console: java.lang.RuntimeException: 解压 C:\Users\user\Desktop\QQBot-wj-test\data\xyz.cssxsh.mirai.plugin.mirai-selenium-plugin\ungoogled-chromium-116.0.5845.141-1_Win64.7z 失败

java.lang.RuntimeException: 解压 C:\Users\user\Desktop\QQBot-wj-test\data\xyz.cssxsh.mirai.plugin.mirai-selenium-plugin\ungoogled-chromium-116.0.5845.141-1_Win64.7z 失败
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt.setupChromium(SeleniumInit.kt:1123)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.MiraiSeleniumPlugin.chromium(MiraiSeleniumPlugin.kt:95)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.command.SeleniumCommand.chromium(SeleniumCommand.kt:116)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.command.SeleniumCommand.chromium$default(SeleniumCommand.kt:113)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: Multi input/output stream coders are not yet supported
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.buildDecoderStack(SevenZFile.java:587)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.reopenFolderInputStream(SevenZFile.java:1591)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.buildDecodingStream(SevenZFile.java:650)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.getInputStream(SevenZFile.java:847)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt.setupChromium(SeleniumInit.kt:1117)
        ... 25 more
```

firefox解压失败
```
 2023-09-01 18:52:48 E/console: java.lang.RuntimeException: 解压 C:\Users\user\Desktop\QQBot-wj-test\data\xyz.cssxsh.mirai.plugin.mirai-selenium-plugin\Firefox Setup 117.0.7z 失败

java.lang.RuntimeException: 解压 C:\Users\user\Desktop\QQBot-wj-test\data\xyz.cssxsh.mirai.plugin.mirai-selenium-plugin\Firefox Setup 117.0.7z 失败
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt.setupFirefox(SeleniumInit.kt:889)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.MiraiSeleniumPlugin.firefox(MiraiSeleniumPlugin.kt:87)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.command.SeleniumCommand.firefox(SeleniumCommand.kt:97)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.command.SeleniumCommand.firefox$default(SeleniumCommand.kt:94)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: Multi input/output stream coders are not yet supported
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.buildDecoderStack(SevenZFile.java:587)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.reopenFolderInputStream(SevenZFile.java:1591)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.buildDecodingStream(SevenZFile.java:650)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[private]//org.apache.commons.compress.archivers.sevenz.SevenZFile.getInputStream(SevenZFile.java:847)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt.setupFirefox(SeleniumInit.kt:883)
        ... 25 more
```

其他疑似的问题：
驱动程序貌似无法安装
```
> selenium clear
清理驱动文件
> selenium setup
安装驱动开始, flush: true
安装驱动成功
> selenium status
当前没有驱动进程
```

依赖此插件的插件报错：

```
 2023-09-01 18:18:48 E/Wiki Search: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of Microsoft Edge WebDriver only supports msedge version 116

Current browser version is 115.0.1901.188 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Host info: host: 'WIN-5QVNL6IIM07', ip: '10.8.0.3'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows Server 2022', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: MicrosoftEdge, ms:edgeOptions: {args: [--silent, --hide-scrollbars, --headless, --remote-allow-origins=*, --user-agent=Mozilla/5.0 (i..., --window-size=768,1024], binary: C:\Program Files (x86)\Micr..., excludeSwitches: [enable-automation, ignore-certificate-errors], extensions: [], prefs: {}}, pageLoadStrategy: normal}]}]
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of Microsoft Edge WebDriver only supports msedge version 116
Current browser version is 115.0.1901.188 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Host info: host: 'WIN-5QVNL6IIM07', ip: '10.8.0.3'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows Server 2022', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: MicrosoftEdge, ms:edgeOptions: {args: [--silent, --hide-scrollbars, --headless, --remote-allow-origins=*, --user-agent=Mozilla/5.0 (i..., --window-size=768,1024], binary: C:\Program Files (x86)\Micr..., excludeSwitches: [enable-automation, ignore-certificate-errors], extensions: [], prefs: {}}, pageLoadStrategy: normal}]}]
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:107)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:59)
        at mirai-selenium-plugin-2.5.0.mirai2.jar[shared]//org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:55)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt$setupEdgeDriver$2.invoke(SeleniumInit.kt:351)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumInitKt$setupEdgeDriver$2.invoke(SeleniumInit.kt:335)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(SeleniumTool.kt:106)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:64)
        at mirai-selenium-plugin-2.5.0.mirai2.jar//xyz.cssxsh.mirai.selenium.MiraiSeleniumPlugin.driver$default(MiraiSeleniumPlugin.kt:63)
        at wiki-search-mirai-0.2.0.mirai2.jar//ltd.guimc.wikisearch.PluginMain$driver$2.invoke(PluginMain.kt:28)
        at wiki-search-mirai-0.2.0.mirai2.jar//ltd.guimc.wikisearch.PluginMain$driver$2.invoke(PluginMain.kt:27)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at wiki-search-mirai-0.2.0.mirai2.jar//ltd.guimc.wikisearch.PluginMain.getDriver(PluginMain.kt:27)
        at wiki-search-mirai-0.2.0.mirai2.jar//ltd.guimc.wikisearch.PluginMain.onEnable(PluginMain.kt:38)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:237)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:308)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:39)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:359)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
```

**Comment by cssxsh** [comment]
为什么你们老是用错误的格式处理日志

**Comment by cssxsh** [comment]
> Caused by: java.io.IOException: Multi input/output stream coders are not yet supported

压缩文件的格式不支持，这是一个已知但是目前无法解决的问题

**Comment by cssxsh** [comment]
处理了一下  `WebDriver only supports`
https://github.com/cssxsh/mirai-selenium-plugin/actions/runs/6053800540

**Comment by seven7a** [comment]
也就是说目前是无法解压7z格式的文件导致的，那我用zip格式打个包，让它解压就能解了吧

**Comment by seven7a** [comment]
> 为什么你们老是用错误的格式处理日志

第一次用代码块功能，去查了下帮助现在改好了

**Comment by seven7a** [comment]
> 也就是说目前是无法解压7z格式的文件导致的，那我用zip格式打个包，让它解压就能解了吧

试了下也是不行的，原来的压缩包有签名校验，问下配置中可以手动设置二进制文件，这里的二进制文件是chrome.dll这个么，设置之后可以解决装不上这个问题么

**Comment by cssxsh** [comment]
补了一个新的 `chrome` 命令
你可以试试

**Comment by seven7a** [comment]
已解决，感谢dalao
