### ISSUE TITLE
和 mirai-login-solver-selenium 插件冲突

### ISSUE THREAD

**Issue by eebssk1** [cssxsh/mirai-selenium-plugin#6]
```
2022-01-02 10:40:19 E/bilibili-helper: Exception in coroutine Plugin xyz.cssxsh.mirai.plugin.bilibili-helper of bilibili-helper
java.lang.ExceptionInInitializerError
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:185)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$2.invoke(SeleniumInit.kt:341)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$2.invoke(SeleniumInit.kt:332)
        at xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(SeleniumTool.kt:58)
        at xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:55)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2$driver$1.invokeSuspend(BiliUtils.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: Unknown HttpClient factory ktor
        at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:54)
        at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:70)
        at org.openqa.selenium.remote.HttpCommandExecutor.<clinit>(HttpCommandExecutor.java:48)
        ... 12 more
```
使用的是Debian11的jre11-headless

**Comment by cssxsh** [comment]
复现失败，请尝试删除 本地的 `bilibili-helper` 和 `mirai-selenium-plugin`，让 mcl 重新下载

**Comment by eebssk1** [comment]
重下还是一样。换了个jdk也还是一样。不过目前不影响使用

**Comment by eebssk1** [comment]
```  12:14:28 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  12:14:28 [INFO] https://github.com/iTXTech/mirai-console-loader
  12:14:28 [INFO] This program is licensed under GNU AGPL v3
  12:14:29 [INFO] Fetching Mirai Console Loader Announcement...
  12:14:31 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

  12:14:31 [INFO] Verifying "net.mamoe:mirai-console" v2.9.1
  12:14:31 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.9.1
  12:14:31 [INFO] Verifying "net.mamoe:mirai-core-all" v2.9.1
  12:14:32 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  12:14:32 [INFO] Verifying "net.mamoe:mirai-login-solver-selenium" v1.0-dev-17
  12:14:32 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  12:14:33 [INFO] Verifying "xyz.cssxsh:bilibili-helper" v1.2.9
  12:14:33 [INFO] Verifying "xyz.cssxsh.mirai:mirai-selenium-plugin" v2.0.0
  12:14:34 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.9.1
2022-01-05 12:14:35 I/main: Starting mirai-console...
2022-01-05 12:14:35 I/main: Backend: version 2.9.1, built on 2021-12-31 04:54:15.
2022-01-05 12:14:35 I/main: Frontend Terminal: version 2.9.1, provided by Mamoe Technologies
2022-01-05 12:14:35 I/main: Welcome to visit https://mirai.mamoe.net/
2022-01-05 12:14:35 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-01-05 12:14:35 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.4.0
2022-01-05 12:14:35 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-01-05 12:14:35 I/net.mamoe.mirai-login-solver-selenium: Loading mirai-login-solver-selenium v1.0-dev-12
2022-01-05 12:14:36 I/plugin: Successfully loaded plugin net.mamoe.mirai-login-solver-selenium v1.0-dev-12
2022-01-05 12:14:36 I/plugin: Successfully loaded plugin bilibili-helper v1.2.9
2022-01-05 12:14:36 I/plugin: Successfully loaded plugin mirai-selenium-plugin v2.0.0
2022-01-05 12:14:36 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-01-05 12:14:37 I/Mirai HTTP API: ********************************************************
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-01-05 12:14:37 I/http adapter: >>> [http adapter] is listening at http://localhost:11991
2022-01-05 12:14:37 I/ws adapter: >>> [ws adapter] is listening at ws://localhost:11991
2022-01-05 12:14:37 I/Mirai HTTP API: Http api server is running with verifyKey: Qwert123
2022-01-05 12:14:37 I/Mirai HTTP API: adaptors: [http,ws]
2022-01-05 12:14:37 I/Mirai HTTP API: ********************************************************
2022-01-05 12:14:37 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2022-01-05 12:14:38 I/bilibili-helper: 加载 SeleniumToolConfig
2022-01-05 12:14:38 I/main: 6 plugin(s) enabled.
[REDACTED]
2022-01-05 12:14:38 E/bilibili-helper: Exception in coroutine Plugin xyz.cssxsh.mirai.plugin.bilibili-helper of bilibili-helper
java.lang.ExceptionInInitializerError
        at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:184)
        at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:185)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$2.invoke(SeleniumInit.kt:341)
        at xyz.cssxsh.selenium.SeleniumInitKt$setupFirefoxDriver$2.invoke(SeleniumInit.kt:332)
        at xyz.cssxsh.selenium.SeleniumToolKt.RemoteWebDriver(SeleniumTool.kt:58)
        at xyz.cssxsh.mirai.plugin.MiraiSeleniumPlugin.driver(MiraiSeleniumPlugin.kt:55)
        at xyz.cssxsh.mirai.plugin.BiliUtilsKt$driver$2$driver$1.invokeSuspend(BiliUtils.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: Unknown HttpClient factory ktor
        at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:54)
        at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:70)
        at org.openqa.selenium.remote.HttpCommandExecutor.<clinit>(HttpCommandExecutor.java:48)
        ... 12 more

ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[REDACTED]
[REDACTED]
[REDACTED]
2022-01-05 12:14:42 I/bilibili-helper: DYNAMIC缓存清理任务开始运行，间隔1h
2022-01-05 12:14:42 I/bilibili-helper: VIDEO缓存清理任务开始运行，间隔1h
2022-01-05 12:14:42 I/bilibili-helper: LIVE缓存清理任务开始运行，间隔1h
2022-01-05 12:14:42 I/bilibili-helper: SEASON缓存清理任务开始运行，间隔1h
2022-01-05 12:14:42 I/bilibili-helper: EPISODE缓存清理任务开始运行，间隔1h
2022-01-05 12:14:42 I/bilibili-helper: USER缓存清理任务开始运行，间隔1h
2022-01-05 12:14:42 I/bilibili-helper: EMOJI缓存清理任务开始运行，间隔1h
[REDACTED]
2022-01-05 12:14:42 I/main: mirai-console started successfully.
```

**Comment by cssxsh** [comment]
> Unknown HttpClient factory ktor

ServiceLoader 没加载上 换一下 `netty` 试试看

**Comment by eebssk1** [comment]
```
Unknown HttpClient factory netty
```
nope
emm玄学，

**Comment by cssxsh** [comment]
> java.lang.J9VMInternals

试试看更换 `java` 版本

**Comment by cssxsh** [comment]
和 `mirai-login-solver-selenium` 插件冲突了，

**Comment by eebssk1** [comment]
删除 ’mirai-login-solver-selenium‘ 后已解决！
